version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: db_1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5423:5432"
    networks:
      - project

  project:
    build:
      context: .
      dockerfile: ../build/package/Dockerfile
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - project

networks:
  project:
    driver: bridge