version: "3.9"

services:
  project:
    build:
      context: .
      dockerfile: ../build/package/Dockerfile
    restart: "no"
    networks:
      - project

networks:
  project:
    driver: bridge

# TODO: postgres
