# Server configuration
server:
  host: "localhost"
  port: 9085

# Database configuration and credentials
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "db_bip"